# Generated by Django 5.0.6 on 2024-06-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_jop_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='description',
            field=models.TextField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jop',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=15),
        ),
    ]
