# Generated by Django 5.0.6 on 2024-06-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jop_description_alter_jop_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='exper',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jop',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jop',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jop',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jop',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
